require 'ffi'

module Eu
  extend FFI::Library
  ffi_lib  File.join(File.dirname(__FILE__),FFI.map_library_name('eu'))
  ExcelType = enum :ExcelEmpty, :ExcelNumber, :ExcelString, :ExcelBoolean, :ExcelError, :ExcelRange
                
  class ExcelValue < FFI::Struct
    layout :type, ExcelType,
  	       :number, :double,
  	       :string, :string,
         	 :array, :pointer,
           :rows, :int,
           :columns, :int             
  end
  

  # use this function to reset all cell values
  attach_function 'reset', [], :void

  # start of EU
  attach_function 'eu_b1', [], ExcelValue.by_value
  attach_function 'eu_d2', [], ExcelValue.by_value
  attach_function 'eu_d3', [], ExcelValue.by_value
  attach_function 'eu_o3', [], ExcelValue.by_value
  attach_function 'eu_b4', [], ExcelValue.by_value
  attach_function 'eu_c4', [], ExcelValue.by_value
  attach_function 'eu_d4', [], ExcelValue.by_value
  attach_function 'eu_e4', [], ExcelValue.by_value
  attach_function 'eu_f4', [], ExcelValue.by_value
  attach_function 'eu_g4', [], ExcelValue.by_value
  attach_function 'eu_h4', [], ExcelValue.by_value
  attach_function 'eu_i4', [], ExcelValue.by_value
  attach_function 'eu_j4', [], ExcelValue.by_value
  attach_function 'eu_k4', [], ExcelValue.by_value
  attach_function 'eu_l4', [], ExcelValue.by_value
  attach_function 'eu_m4', [], ExcelValue.by_value
  attach_function 'eu_o4', [], ExcelValue.by_value
  attach_function 'eu_b5', [], ExcelValue.by_value
  attach_function 'eu_c5', [], ExcelValue.by_value
  attach_function 'eu_d5', [], ExcelValue.by_value
  attach_function 'eu_e5', [], ExcelValue.by_value
  attach_function 'eu_f5', [], ExcelValue.by_value
  attach_function 'eu_g5', [], ExcelValue.by_value
  attach_function 'eu_h5', [], ExcelValue.by_value
  attach_function 'eu_i5', [], ExcelValue.by_value
  attach_function 'eu_j5', [], ExcelValue.by_value
  attach_function 'eu_k5', [], ExcelValue.by_value
  attach_function 'eu_l5', [], ExcelValue.by_value
  attach_function 'eu_m5', [], ExcelValue.by_value
  attach_function 'eu_n5', [], ExcelValue.by_value
  attach_function 'eu_o5', [], ExcelValue.by_value
  attach_function 'eu_b6', [], ExcelValue.by_value
  attach_function 'eu_c6', [], ExcelValue.by_value
  attach_function 'eu_f6', [], ExcelValue.by_value
  attach_function 'eu_g6', [], ExcelValue.by_value
  attach_function 'eu_h6', [], ExcelValue.by_value
  attach_function 'eu_i6', [], ExcelValue.by_value
  attach_function 'eu_j6', [], ExcelValue.by_value
  attach_function 'eu_k6', [], ExcelValue.by_value
  attach_function 'eu_l6', [], ExcelValue.by_value
  attach_function 'eu_m6', [], ExcelValue.by_value
  attach_function 'eu_n6', [], ExcelValue.by_value
  attach_function 'eu_o6', [], ExcelValue.by_value
  attach_function 'eu_b7', [], ExcelValue.by_value
  attach_function 'eu_c7', [], ExcelValue.by_value
  attach_function 'eu_d7', [], ExcelValue.by_value
  attach_function 'eu_e7', [], ExcelValue.by_value
  attach_function 'eu_f7', [], ExcelValue.by_value
  attach_function 'eu_g7', [], ExcelValue.by_value
  attach_function 'eu_h7', [], ExcelValue.by_value
  attach_function 'eu_i7', [], ExcelValue.by_value
  attach_function 'eu_j7', [], ExcelValue.by_value
  attach_function 'eu_k7', [], ExcelValue.by_value
  attach_function 'eu_l7', [], ExcelValue.by_value
  attach_function 'eu_m7', [], ExcelValue.by_value
  attach_function 'eu_n7', [], ExcelValue.by_value
  attach_function 'eu_o7', [], ExcelValue.by_value
  attach_function 'eu_b8', [], ExcelValue.by_value
  attach_function 'eu_f8', [], ExcelValue.by_value
  attach_function 'eu_g8', [], ExcelValue.by_value
  attach_function 'eu_h8', [], ExcelValue.by_value
  attach_function 'eu_i8', [], ExcelValue.by_value
  attach_function 'eu_j8', [], ExcelValue.by_value
  attach_function 'eu_k8', [], ExcelValue.by_value
  attach_function 'eu_l8', [], ExcelValue.by_value
  attach_function 'eu_m8', [], ExcelValue.by_value
  attach_function 'eu_n8', [], ExcelValue.by_value
  attach_function 'eu_b10', [], ExcelValue.by_value
  attach_function 'eu_f10', [], ExcelValue.by_value
  attach_function 'eu_g10', [], ExcelValue.by_value
  attach_function 'eu_h10', [], ExcelValue.by_value
  attach_function 'eu_i10', [], ExcelValue.by_value
  attach_function 'eu_j10', [], ExcelValue.by_value
  attach_function 'eu_k10', [], ExcelValue.by_value
  attach_function 'eu_l10', [], ExcelValue.by_value
  attach_function 'eu_m10', [], ExcelValue.by_value
  attach_function 'eu_b11', [], ExcelValue.by_value
  attach_function 'eu_f11', [], ExcelValue.by_value
  attach_function 'eu_g11', [], ExcelValue.by_value
  attach_function 'eu_h11', [], ExcelValue.by_value
  attach_function 'eu_i11', [], ExcelValue.by_value
  attach_function 'eu_j11', [], ExcelValue.by_value
  attach_function 'eu_k11', [], ExcelValue.by_value
  attach_function 'eu_l11', [], ExcelValue.by_value
  attach_function 'eu_m11', [], ExcelValue.by_value
  attach_function 'eu_n11', [], ExcelValue.by_value
  attach_function 'eu_b12', [], ExcelValue.by_value
  attach_function 'eu_f12', [], ExcelValue.by_value
  attach_function 'eu_g12', [], ExcelValue.by_value
  attach_function 'eu_h12', [], ExcelValue.by_value
  attach_function 'eu_i12', [], ExcelValue.by_value
  attach_function 'eu_j12', [], ExcelValue.by_value
  attach_function 'eu_k12', [], ExcelValue.by_value
  attach_function 'eu_l12', [], ExcelValue.by_value
  attach_function 'eu_m12', [], ExcelValue.by_value
  attach_function 'eu_o12', [], ExcelValue.by_value
  attach_function 'eu_b13', [], ExcelValue.by_value
  attach_function 'eu_f13', [], ExcelValue.by_value
  attach_function 'eu_g13', [], ExcelValue.by_value
  attach_function 'eu_h13', [], ExcelValue.by_value
  attach_function 'eu_i13', [], ExcelValue.by_value
  attach_function 'eu_j13', [], ExcelValue.by_value
  attach_function 'eu_k13', [], ExcelValue.by_value
  attach_function 'eu_l13', [], ExcelValue.by_value
  attach_function 'eu_m13', [], ExcelValue.by_value
  attach_function 'eu_n13', [], ExcelValue.by_value
  attach_function 'eu_o13', [], ExcelValue.by_value
  attach_function 'eu_b14', [], ExcelValue.by_value
  attach_function 'eu_f14', [], ExcelValue.by_value
  attach_function 'eu_g14', [], ExcelValue.by_value
  attach_function 'eu_h14', [], ExcelValue.by_value
  attach_function 'eu_i14', [], ExcelValue.by_value
  attach_function 'eu_j14', [], ExcelValue.by_value
  attach_function 'eu_k14', [], ExcelValue.by_value
  attach_function 'eu_l14', [], ExcelValue.by_value
  attach_function 'eu_m14', [], ExcelValue.by_value
  attach_function 'eu_b15', [], ExcelValue.by_value
  attach_function 'eu_f15', [], ExcelValue.by_value
  attach_function 'eu_g15', [], ExcelValue.by_value
  attach_function 'eu_h15', [], ExcelValue.by_value
  attach_function 'eu_i15', [], ExcelValue.by_value
  attach_function 'eu_j15', [], ExcelValue.by_value
  attach_function 'eu_k15', [], ExcelValue.by_value
  attach_function 'eu_l15', [], ExcelValue.by_value
  attach_function 'eu_m15', [], ExcelValue.by_value
  attach_function 'eu_n15', [], ExcelValue.by_value
  attach_function 'eu_b17', [], ExcelValue.by_value
  attach_function 'eu_f17', [], ExcelValue.by_value
  attach_function 'eu_g17', [], ExcelValue.by_value
  attach_function 'eu_h17', [], ExcelValue.by_value
  attach_function 'eu_i17', [], ExcelValue.by_value
  attach_function 'eu_j17', [], ExcelValue.by_value
  attach_function 'eu_k17', [], ExcelValue.by_value
  attach_function 'eu_l17', [], ExcelValue.by_value
  attach_function 'eu_m17', [], ExcelValue.by_value
  attach_function 'eu_b18', [], ExcelValue.by_value
  attach_function 'eu_d18', [], ExcelValue.by_value
  attach_function 'eu_f18', [], ExcelValue.by_value
  attach_function 'eu_g18', [], ExcelValue.by_value
  attach_function 'eu_h18', [], ExcelValue.by_value
  attach_function 'eu_i18', [], ExcelValue.by_value
  attach_function 'eu_j18', [], ExcelValue.by_value
  attach_function 'eu_k18', [], ExcelValue.by_value
  attach_function 'eu_l18', [], ExcelValue.by_value
  attach_function 'eu_m18', [], ExcelValue.by_value
  attach_function 'eu_b19', [], ExcelValue.by_value
  attach_function 'eu_d19', [], ExcelValue.by_value
  attach_function 'eu_f19', [], ExcelValue.by_value
  attach_function 'eu_g19', [], ExcelValue.by_value
  attach_function 'eu_h19', [], ExcelValue.by_value
  attach_function 'eu_i19', [], ExcelValue.by_value
  attach_function 'eu_j19', [], ExcelValue.by_value
  attach_function 'eu_k19', [], ExcelValue.by_value
  attach_function 'eu_l19', [], ExcelValue.by_value
  attach_function 'eu_m19', [], ExcelValue.by_value
  attach_function 'eu_o19', [], ExcelValue.by_value
  attach_function 'eu_p19', [], ExcelValue.by_value
  attach_function 'eu_b20', [], ExcelValue.by_value
  attach_function 'eu_f20', [], ExcelValue.by_value
  attach_function 'eu_g20', [], ExcelValue.by_value
  attach_function 'eu_h20', [], ExcelValue.by_value
  attach_function 'eu_i20', [], ExcelValue.by_value
  attach_function 'eu_j20', [], ExcelValue.by_value
  attach_function 'eu_k20', [], ExcelValue.by_value
  attach_function 'eu_l20', [], ExcelValue.by_value
  attach_function 'eu_m20', [], ExcelValue.by_value
  attach_function 'eu_b21', [], ExcelValue.by_value
  attach_function 'eu_f21', [], ExcelValue.by_value
  attach_function 'eu_g21', [], ExcelValue.by_value
  attach_function 'eu_h21', [], ExcelValue.by_value
  attach_function 'eu_i21', [], ExcelValue.by_value
  attach_function 'eu_j21', [], ExcelValue.by_value
  attach_function 'eu_k21', [], ExcelValue.by_value
  attach_function 'eu_l21', [], ExcelValue.by_value
  attach_function 'eu_m21', [], ExcelValue.by_value
  attach_function 'eu_b23', [], ExcelValue.by_value
  attach_function 'eu_f23', [], ExcelValue.by_value
  attach_function 'eu_g23', [], ExcelValue.by_value
  attach_function 'eu_h23', [], ExcelValue.by_value
  attach_function 'eu_i23', [], ExcelValue.by_value
  attach_function 'eu_j23', [], ExcelValue.by_value
  attach_function 'eu_k23', [], ExcelValue.by_value
  attach_function 'eu_l23', [], ExcelValue.by_value
  attach_function 'eu_m23', [], ExcelValue.by_value
  attach_function 'eu_b24', [], ExcelValue.by_value
  attach_function 'eu_f24', [], ExcelValue.by_value
  attach_function 'eu_g24', [], ExcelValue.by_value
  attach_function 'eu_h24', [], ExcelValue.by_value
  attach_function 'eu_i24', [], ExcelValue.by_value
  attach_function 'eu_j24', [], ExcelValue.by_value
  attach_function 'eu_k24', [], ExcelValue.by_value
  attach_function 'eu_l24', [], ExcelValue.by_value
  attach_function 'eu_m24', [], ExcelValue.by_value
  attach_function 'eu_n24', [], ExcelValue.by_value
  attach_function 'eu_o24', [], ExcelValue.by_value
  attach_function 'eu_b25', [], ExcelValue.by_value
  attach_function 'eu_f25', [], ExcelValue.by_value
  attach_function 'eu_g25', [], ExcelValue.by_value
  attach_function 'eu_h25', [], ExcelValue.by_value
  attach_function 'eu_i25', [], ExcelValue.by_value
  attach_function 'eu_j25', [], ExcelValue.by_value
  attach_function 'eu_k25', [], ExcelValue.by_value
  attach_function 'eu_l25', [], ExcelValue.by_value
  attach_function 'eu_m25', [], ExcelValue.by_value
  attach_function 'eu_b27', [], ExcelValue.by_value
  attach_function 'eu_f27', [], ExcelValue.by_value
  attach_function 'eu_g27', [], ExcelValue.by_value
  attach_function 'eu_h27', [], ExcelValue.by_value
  attach_function 'eu_i27', [], ExcelValue.by_value
  attach_function 'eu_j27', [], ExcelValue.by_value
  attach_function 'eu_k27', [], ExcelValue.by_value
  attach_function 'eu_l27', [], ExcelValue.by_value
  attach_function 'eu_m27', [], ExcelValue.by_value
  attach_function 'eu_b28', [], ExcelValue.by_value
  attach_function 'eu_f28', [], ExcelValue.by_value
  attach_function 'eu_g28', [], ExcelValue.by_value
  attach_function 'eu_h28', [], ExcelValue.by_value
  attach_function 'eu_i28', [], ExcelValue.by_value
  attach_function 'eu_j28', [], ExcelValue.by_value
  attach_function 'eu_k28', [], ExcelValue.by_value
  attach_function 'eu_l28', [], ExcelValue.by_value
  attach_function 'eu_m28', [], ExcelValue.by_value
  attach_function 'eu_b29', [], ExcelValue.by_value
  attach_function 'eu_f29', [], ExcelValue.by_value
  attach_function 'eu_g29', [], ExcelValue.by_value
  attach_function 'eu_h29', [], ExcelValue.by_value
  attach_function 'eu_i29', [], ExcelValue.by_value
  attach_function 'eu_j29', [], ExcelValue.by_value
  attach_function 'eu_k29', [], ExcelValue.by_value
  attach_function 'eu_l29', [], ExcelValue.by_value
  attach_function 'eu_m29', [], ExcelValue.by_value
  attach_function 'eu_b30', [], ExcelValue.by_value
  attach_function 'eu_f30', [], ExcelValue.by_value
  attach_function 'eu_g30', [], ExcelValue.by_value
  attach_function 'eu_h30', [], ExcelValue.by_value
  attach_function 'eu_i30', [], ExcelValue.by_value
  attach_function 'eu_j30', [], ExcelValue.by_value
  attach_function 'eu_k30', [], ExcelValue.by_value
  attach_function 'eu_l30', [], ExcelValue.by_value
  attach_function 'eu_m30', [], ExcelValue.by_value
  attach_function 'eu_b31', [], ExcelValue.by_value
  attach_function 'eu_f31', [], ExcelValue.by_value
  attach_function 'eu_g31', [], ExcelValue.by_value
  attach_function 'eu_h31', [], ExcelValue.by_value
  attach_function 'eu_i31', [], ExcelValue.by_value
  attach_function 'eu_j31', [], ExcelValue.by_value
  attach_function 'eu_k31', [], ExcelValue.by_value
  attach_function 'eu_l31', [], ExcelValue.by_value
  attach_function 'eu_m31', [], ExcelValue.by_value
  attach_function 'eu_b33', [], ExcelValue.by_value
  attach_function 'eu_b34', [], ExcelValue.by_value
  attach_function 'eu_f34', [], ExcelValue.by_value
  attach_function 'eu_g34', [], ExcelValue.by_value
  attach_function 'eu_h34', [], ExcelValue.by_value
  attach_function 'eu_i34', [], ExcelValue.by_value
  attach_function 'eu_j34', [], ExcelValue.by_value
  attach_function 'eu_k34', [], ExcelValue.by_value
  attach_function 'eu_l34', [], ExcelValue.by_value
  attach_function 'eu_m34', [], ExcelValue.by_value
  attach_function 'eu_b35', [], ExcelValue.by_value
  attach_function 'eu_f35', [], ExcelValue.by_value
  attach_function 'eu_g35', [], ExcelValue.by_value
  attach_function 'eu_h35', [], ExcelValue.by_value
  attach_function 'eu_i35', [], ExcelValue.by_value
  attach_function 'eu_j35', [], ExcelValue.by_value
  attach_function 'eu_k35', [], ExcelValue.by_value
  attach_function 'eu_l35', [], ExcelValue.by_value
  attach_function 'eu_m35', [], ExcelValue.by_value
  attach_function 'eu_b39', [], ExcelValue.by_value
  attach_function 'eu_f39', [], ExcelValue.by_value
  attach_function 'eu_g39', [], ExcelValue.by_value
  attach_function 'eu_n39', [], ExcelValue.by_value
  attach_function 'eu_b40', [], ExcelValue.by_value
  attach_function 'eu_f40', [], ExcelValue.by_value
  attach_function 'eu_g40', [], ExcelValue.by_value
  attach_function 'eu_b41', [], ExcelValue.by_value
  attach_function 'eu_f41', [], ExcelValue.by_value
  attach_function 'eu_b42', [], ExcelValue.by_value
  attach_function 'eu_f42', [], ExcelValue.by_value
  attach_function 'eu_b43', [], ExcelValue.by_value
  attach_function 'eu_f43', [], ExcelValue.by_value
  attach_function 'eu_b45', [], ExcelValue.by_value
  attach_function 'eu_f45', [], ExcelValue.by_value
  attach_function 'eu_g45', [], ExcelValue.by_value
  attach_function 'eu_h45', [], ExcelValue.by_value
  attach_function 'eu_i45', [], ExcelValue.by_value
  attach_function 'eu_j45', [], ExcelValue.by_value
  attach_function 'eu_k45', [], ExcelValue.by_value
  attach_function 'eu_l45', [], ExcelValue.by_value
  attach_function 'eu_m45', [], ExcelValue.by_value
  attach_function 'eu_b46', [], ExcelValue.by_value
  attach_function 'eu_f46', [], ExcelValue.by_value
  attach_function 'eu_g46', [], ExcelValue.by_value
  attach_function 'eu_h46', [], ExcelValue.by_value
  attach_function 'eu_i46', [], ExcelValue.by_value
  attach_function 'eu_j46', [], ExcelValue.by_value
  attach_function 'eu_k46', [], ExcelValue.by_value
  attach_function 'eu_l46', [], ExcelValue.by_value
  attach_function 'eu_m46', [], ExcelValue.by_value
  attach_function 'eu_n46', [], ExcelValue.by_value
  # end of EU

  # start of OLD UK
  attach_function 'old_uk_b2', [], ExcelValue.by_value
  attach_function 'old_uk_b4', [], ExcelValue.by_value
  attach_function 'old_uk_c4', [], ExcelValue.by_value
  attach_function 'old_uk_d4', [], ExcelValue.by_value
  attach_function 'old_uk_e4', [], ExcelValue.by_value
  attach_function 'old_uk_f4', [], ExcelValue.by_value
  attach_function 'old_uk_g4', [], ExcelValue.by_value
  attach_function 'old_uk_h4', [], ExcelValue.by_value
  attach_function 'old_uk_i4', [], ExcelValue.by_value
  attach_function 'old_uk_j4', [], ExcelValue.by_value
  attach_function 'old_uk_l4', [], ExcelValue.by_value
  attach_function 'old_uk_b5', [], ExcelValue.by_value
  attach_function 'old_uk_c5', [], ExcelValue.by_value
  attach_function 'old_uk_d5', [], ExcelValue.by_value
  attach_function 'old_uk_e5', [], ExcelValue.by_value
  attach_function 'old_uk_f5', [], ExcelValue.by_value
  attach_function 'old_uk_g5', [], ExcelValue.by_value
  attach_function 'old_uk_h5', [], ExcelValue.by_value
  attach_function 'old_uk_i5', [], ExcelValue.by_value
  attach_function 'old_uk_j5', [], ExcelValue.by_value
  attach_function 'old_uk_k5', [], ExcelValue.by_value
  attach_function 'old_uk_l5', [], ExcelValue.by_value
  attach_function 'old_uk_b6', [], ExcelValue.by_value
  attach_function 'old_uk_c6', [], ExcelValue.by_value
  attach_function 'old_uk_d6', [], ExcelValue.by_value
  attach_function 'old_uk_e6', [], ExcelValue.by_value
  attach_function 'old_uk_f6', [], ExcelValue.by_value
  attach_function 'old_uk_g6', [], ExcelValue.by_value
  attach_function 'old_uk_h6', [], ExcelValue.by_value
  attach_function 'old_uk_i6', [], ExcelValue.by_value
  attach_function 'old_uk_j6', [], ExcelValue.by_value
  attach_function 'old_uk_k6', [], ExcelValue.by_value
  attach_function 'old_uk_l6', [], ExcelValue.by_value
  attach_function 'old_uk_b7', [], ExcelValue.by_value
  attach_function 'old_uk_c7', [], ExcelValue.by_value
  attach_function 'old_uk_d7', [], ExcelValue.by_value
  attach_function 'old_uk_e7', [], ExcelValue.by_value
  attach_function 'old_uk_f7', [], ExcelValue.by_value
  attach_function 'old_uk_g7', [], ExcelValue.by_value
  attach_function 'old_uk_h7', [], ExcelValue.by_value
  attach_function 'old_uk_i7', [], ExcelValue.by_value
  attach_function 'old_uk_j7', [], ExcelValue.by_value
  attach_function 'old_uk_k7', [], ExcelValue.by_value
  attach_function 'old_uk_l7', [], ExcelValue.by_value
  attach_function 'old_uk_b9', [], ExcelValue.by_value
  attach_function 'old_uk_c9', [], ExcelValue.by_value
  attach_function 'old_uk_d9', [], ExcelValue.by_value
  attach_function 'old_uk_e9', [], ExcelValue.by_value
  attach_function 'old_uk_f9', [], ExcelValue.by_value
  attach_function 'old_uk_g9', [], ExcelValue.by_value
  attach_function 'old_uk_h9', [], ExcelValue.by_value
  attach_function 'old_uk_i9', [], ExcelValue.by_value
  attach_function 'old_uk_j9', [], ExcelValue.by_value
  attach_function 'old_uk_b10', [], ExcelValue.by_value
  attach_function 'old_uk_c10', [], ExcelValue.by_value
  attach_function 'old_uk_d10', [], ExcelValue.by_value
  attach_function 'old_uk_e10', [], ExcelValue.by_value
  attach_function 'old_uk_f10', [], ExcelValue.by_value
  attach_function 'old_uk_g10', [], ExcelValue.by_value
  attach_function 'old_uk_h10', [], ExcelValue.by_value
  attach_function 'old_uk_i10', [], ExcelValue.by_value
  attach_function 'old_uk_j10', [], ExcelValue.by_value
  attach_function 'old_uk_k10', [], ExcelValue.by_value
  attach_function 'old_uk_b11', [], ExcelValue.by_value
  attach_function 'old_uk_c11', [], ExcelValue.by_value
  attach_function 'old_uk_d11', [], ExcelValue.by_value
  attach_function 'old_uk_e11', [], ExcelValue.by_value
  attach_function 'old_uk_f11', [], ExcelValue.by_value
  attach_function 'old_uk_g11', [], ExcelValue.by_value
  attach_function 'old_uk_h11', [], ExcelValue.by_value
  attach_function 'old_uk_i11', [], ExcelValue.by_value
  attach_function 'old_uk_j11', [], ExcelValue.by_value
  attach_function 'old_uk_k11', [], ExcelValue.by_value
  attach_function 'old_uk_l11', [], ExcelValue.by_value
  attach_function 'old_uk_b12', [], ExcelValue.by_value
  attach_function 'old_uk_c12', [], ExcelValue.by_value
  attach_function 'old_uk_d12', [], ExcelValue.by_value
  attach_function 'old_uk_e12', [], ExcelValue.by_value
  attach_function 'old_uk_f12', [], ExcelValue.by_value
  attach_function 'old_uk_g12', [], ExcelValue.by_value
  attach_function 'old_uk_h12', [], ExcelValue.by_value
  attach_function 'old_uk_i12', [], ExcelValue.by_value
  attach_function 'old_uk_j12', [], ExcelValue.by_value
  attach_function 'old_uk_k12', [], ExcelValue.by_value
  attach_function 'old_uk_c14', [], ExcelValue.by_value
  attach_function 'old_uk_d14', [], ExcelValue.by_value
  attach_function 'old_uk_e14', [], ExcelValue.by_value
  attach_function 'old_uk_f14', [], ExcelValue.by_value
  attach_function 'old_uk_g14', [], ExcelValue.by_value
  attach_function 'old_uk_h14', [], ExcelValue.by_value
  attach_function 'old_uk_i14', [], ExcelValue.by_value
  attach_function 'old_uk_j14', [], ExcelValue.by_value
  attach_function 'old_uk_b15', [], ExcelValue.by_value
  attach_function 'old_uk_c15', [], ExcelValue.by_value
  attach_function 'old_uk_d15', [], ExcelValue.by_value
  attach_function 'old_uk_e15', [], ExcelValue.by_value
  attach_function 'old_uk_f15', [], ExcelValue.by_value
  attach_function 'old_uk_g15', [], ExcelValue.by_value
  attach_function 'old_uk_h15', [], ExcelValue.by_value
  attach_function 'old_uk_i15', [], ExcelValue.by_value
  attach_function 'old_uk_j15', [], ExcelValue.by_value
  attach_function 'old_uk_k15', [], ExcelValue.by_value
  attach_function 'old_uk_b17', [], ExcelValue.by_value
  attach_function 'old_uk_c17', [], ExcelValue.by_value
  attach_function 'old_uk_d17', [], ExcelValue.by_value
  attach_function 'old_uk_e17', [], ExcelValue.by_value
  attach_function 'old_uk_f17', [], ExcelValue.by_value
  attach_function 'old_uk_g17', [], ExcelValue.by_value
  attach_function 'old_uk_h17', [], ExcelValue.by_value
  attach_function 'old_uk_i17', [], ExcelValue.by_value
  attach_function 'old_uk_j17', [], ExcelValue.by_value
  attach_function 'old_uk_b18', [], ExcelValue.by_value
  attach_function 'old_uk_c18', [], ExcelValue.by_value
  attach_function 'old_uk_d18', [], ExcelValue.by_value
  attach_function 'old_uk_e18', [], ExcelValue.by_value
  attach_function 'old_uk_f18', [], ExcelValue.by_value
  attach_function 'old_uk_g18', [], ExcelValue.by_value
  attach_function 'old_uk_h18', [], ExcelValue.by_value
  attach_function 'old_uk_i18', [], ExcelValue.by_value
  attach_function 'old_uk_j18', [], ExcelValue.by_value
  attach_function 'old_uk_k18', [], ExcelValue.by_value
  attach_function 'old_uk_b19', [], ExcelValue.by_value
  attach_function 'old_uk_c19', [], ExcelValue.by_value
  attach_function 'old_uk_d19', [], ExcelValue.by_value
  attach_function 'old_uk_e19', [], ExcelValue.by_value
  attach_function 'old_uk_f19', [], ExcelValue.by_value
  attach_function 'old_uk_g19', [], ExcelValue.by_value
  attach_function 'old_uk_h19', [], ExcelValue.by_value
  attach_function 'old_uk_i19', [], ExcelValue.by_value
  attach_function 'old_uk_j19', [], ExcelValue.by_value
  attach_function 'old_uk_k19', [], ExcelValue.by_value
  attach_function 'old_uk_b20', [], ExcelValue.by_value
  attach_function 'old_uk_c20', [], ExcelValue.by_value
  attach_function 'old_uk_d20', [], ExcelValue.by_value
  attach_function 'old_uk_e20', [], ExcelValue.by_value
  attach_function 'old_uk_f20', [], ExcelValue.by_value
  attach_function 'old_uk_g20', [], ExcelValue.by_value
  attach_function 'old_uk_h20', [], ExcelValue.by_value
  attach_function 'old_uk_i20', [], ExcelValue.by_value
  attach_function 'old_uk_j20', [], ExcelValue.by_value
  attach_function 'old_uk_k20', [], ExcelValue.by_value
  attach_function 'old_uk_k22', [], ExcelValue.by_value
  # end of OLD UK
end
